export { default as About } from './About';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as SearchBar } from './SearchBar';
export { default as NotFound } from './NotFound';
export { default as SearchList } from './SearchList';
export { default as ShoppingCart } from './ShoppingCart';
export { default as Categories } from './Categories';
export { default as Home } from './Home';
